### ISSUE TITLE
Meaning of the option "--stdin"

### ISSUE THREAD

**Issue by funcrab** [Omochice/deepl-translate-cli#8]
I'm sorry if I misunderstood something.
What is the point of having the option `--stdin`?
If it's required for normal use, can't it be made to work without the option?

**Comment by Omochice** [comment]
The `--stdin` option is provided to clearly distinguish whether a filename is specified as an argument.
However, if the number of arguments is 0, it can automatically change to `stdin` mode.
It may be useful as it reduces the number of typings.

I will change it.

Thanks.

**Comment by Omochice** [comment]
I release v0.0.11.
It should be work without `--stdin`.
